import esbuild from "esbuild";
import process from "process";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import { createRequire } from "module";
import { readFile } from "fs/promises";
import { compile, compileModule } from "svelte/compiler";

const require = createRequire(import.meta.url);
const pkg = require("./package.json");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...Object.keys(pkg.dependencies || {}),
		...Object.keys(pkg.peerDependencies || {}),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: "svelte-module",
			setup(build) {
				build.onLoad({ filter: /\.svelte\.(ts|js)$/ }, async (args) => {
					const source = await readFile(args.path, "utf8");
					const filename = args.path;

					// Strip types if TS
					const { code } = await esbuild.transform(source, { loader: "ts" });

					// Compile with Svelte
					// Force filename to end in .svelte.js to ensure module mode
					const virtualFilename = filename.replace(/\.svelte\.ts$/, ".svelte.js");

					const compiled = compileModule(code, {
						filename: virtualFilename,
					});

					return {
						contents: compiled.js.code,
						loader: "js",
					};
				});
			},
		},
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
			include: /\.svelte$/,
		}),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
